Fixing clippy iotedged
Azure/iotedge pull request #3696
Opened 2020-10-09 21:09 UTC by huguesBouvier

Fixing Clippy issues

2020-10-09 22:09 UTC, lfitchett submitted a review, later dismissed

2020-10-09 22:52 UTC, arsing requested changes

2020-10-09 22:52 UTC, arsing commented on edgelet/dps/src/registration.rs
> +        let c = token_source.map_or(client.read().expect("RwLock read failure").clone(), |ts| {
`.map_or_else`

2020-10-09 22:52 UTC, arsing commented on edgelet/edgelet-iothub/src/lib.rs
> +        let result = id.generation_id().map_or(
`.map_or_else`

2020-10-09 22:52 UTC, arsing commented on edgelet/iotedge/src/check/checks/connect_management_uri.rs
> +            settings.parent_hostname().map_or(
`.map_or_else`

2020-10-09 22:52 UTC, arsing commented on edgelet/iotedge/src/check/checks/container_connect_upstream.rs
> +            settings.parent_hostname().map_or(
`.map_or_else`

2020-10-09 22:52 UTC, arsing commented on edgelet/iotedge/src/check/checks/container_local_time.rs
> +            settings.parent_hostname().map_or(
`.map_or_else`

2020-10-09 22:52 UTC, arsing commented on edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
> +            settings.parent_hostname().map_or(
`.map_or_else`

2020-10-09 23:38 UTC, huguesBouvier commented on edgelet/dps/src/registration.rs
> +        let c = token_source.map_or(client.read().expect("RwLock read failure").clone(), |ts| {
Fixed.

2020-10-09 23:40 UTC, huguesBouvier commented on edgelet/edgelet-iothub/src/lib.rs
> +        let result = id.generation_id().map_or(
Fixed.

2020-10-09 23:40 UTC, huguesBouvier commented on edgelet/iotedge/src/check/checks/connect_management_uri.rs
> +            settings.parent_hostname().map_or(
Fixed.

2020-10-09 23:40 UTC, huguesBouvier commented on edgelet/iotedge/src/check/checks/container_local_time.rs
> +            settings.parent_hostname().map_or(
Fixed.

2020-10-09 23:41 UTC, huguesBouvier commented on edgelet/iotedge/src/check/checks/container_connect_upstream.rs
> +            settings.parent_hostname().map_or(
Fixed.

2020-10-09 23:41 UTC, huguesBouvier commented on edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
> +            settings.parent_hostname().map_or(
Fixed.

2020-10-10 02:02 UTC, arsing commented on edgelet/edgelet-iothub/src/lib.rs
> +        let result = id.generation_id().map_or(
Hasn't been fixed.

2020-10-10 02:04 UTC, arsing requested changes
.

2020-10-10 03:08 UTC, huguesBouvier commented on edgelet/edgelet-iothub/src/lib.rs
> +        let result = id.generation_id().map_or(
didn't get pushed. Fixed.

2020-10-10 08:48 UTC, arsing approved these changes

2020-10-12 17:07 UTC, merged