Added FeatureFlagAuthorizer to wrap PolicyAuthorizer
Azure/iotedge pull request #3802
Opened 2020-10-26 16:51 UTC by vadim-kovalyov

Since policy engine requires default configuration, we needed to wrap `PolicyAuthorizer` with a feature flag, so it does not interfere with existing e2e tests. Otherwise all existing e2e tests needs to be fixed to include policy engine configuration.

2020-10-26 17:00 UTC, dmolokanov submitted a review, later dismissed
I believe it is temporal thing and to be removed as soon as you fix tests. If my assumption is not correct please import structs/traits with use block instead of FQN.

2020-10-26 17:14 UTC, vadim-kovalyov commented
> I believe it is temporal thing and to be removed as soon as you fix tests. If my assumption is not correct please import structs/traits with use block instead of FQN.

Nothing more permanent than temporary :) But I believe it should go away when MQTT broker flag goes away.

2020-10-26 18:06 UTC, varunpuranik commented on mqtt/mqttd/src/broker/bootstrap/edgehub.rs
> +const POLICY_ENABLED_ENV: &str = "experimentalFeatures:policyEngineEnabled";
We should just use the experimentalFeatures:mqttBrokerEnabled feature flag.

2020-10-26 18:07 UTC, varunpuranik requested changes
Why do we need to add a new flag just for the policy engine?

2020-10-26 23:25 UTC, dmolokanov commented on mqtt/mqttd/src/broker/bootstrap/edgehub.rs
> +    let authorizer = LocalAuthorizer::new(EdgeHubAuthorizer::new(
curious if we could just select here in place: 
```rust
env::var(POLICY_ENABLED_ENV).ok().map_or_else(||AllowAll, |_| PolicyAuthorizer::new(device_id, broker_ready.handle()))
```

2020-10-26 23:25 UTC, dmolokanov approved these changes

2020-10-29 22:49 UTC, vadim-kovalyov commented
No longer required.

2020-10-29 22:49 UTC, closed without merging