Prepare for release 1.0.10.2
Azure/iotedge pull request #3955
Opened 2020-11-11 21:13 UTC by damonbarry

2020-11-11 21:15 UTC, lfitchett submitted a review, later dismissed

2020-11-11 21:32 UTC, varunpuranik requested changes
We also need to update this file - https://github.com/Azure/iotedge/blob/release/1.0.10/versionInfo.json

2020-11-11 21:34 UTC, damonbarry commented
> We also need to update this file - https://github.com/Azure/iotedge/blob/release/1.0.10/versionInfo.json

@varunpuranik That file is used by Edge agent and Edge hub to report the version in their logs. Since we're not bumping agent and hub, I don't think we should update that file.

2020-11-11 21:59 UTC, varunpuranik approved these changes

2020-11-12 00:33 UTC, varunpuranik approved these changes

2020-11-12 00:33 UTC, lfitchett approved these changes

2020-11-12 00:48 UTC, arsing approved these changes

2020-11-12 01:13 UTC, merged