Introduce nested edge device connection to grandparent verification test
Azure/iotedge pull request #4538
Opened 2021-03-04 00:49 UTC by yophilav

- Introduce nested edge device connection to grandparent verification test

2021-03-08 18:22 UTC, ancaantochi commented on test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs
> +            public readonly string DeviceHostname;
these should be properties: public string DeviceHostname { get; }

2021-03-08 18:25 UTC, ancaantochi commented on test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs
> +            NestedEdgeConfig nestedEdgeConfig = default(NestedEdgeConfig))
preferred to use Option instead of null

2021-03-08 18:26 UTC, ancaantochi commented on test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
> +                $"GatewayHostName={this.device.NestedEdge.DeviceHostname}";
is the ToLower() required, just wondering if this can cause the test issue

2021-03-11 18:57 UTC, huguesBouvier requested changes
Hey, ran the E2E test on this PR: https://dev.azure.com/msazure/One/_build/results?buildId=40273660&view=results
But got the following issues:
1. only a subset of test are running => Remove your debug only
2. Some test are failing:TransparentGateway

You can compare with a recent run on master: https://dev.azure.com/msazure/One/_build/results?buildId=40275354&view=logs&j=e8afecc0-c259-5cc1-62e0-5c5d1c2a3db4

2021-03-11 18:58 UTC, huguesBouvier commented on builds/e2e/templates/e2e-run.yaml
> +    # BEARWASHERE -- DEBUG ONLY
Bear should not be in production code :)

2021-03-24 02:04 UTC, yophilav commented
Do you believe in Code Fermentation? 
Without changing a thing, it seems like my code is now passing on this test run: 
https://msazure.visualstudio.com/One/_build/results?buildId=40699021&view=results

2021-03-24 23:29 UTC, huguesBouvier requested changes
Looking at your run on nested E2E, several tests are failing. Let's dig into them

2021-03-27 00:22 UTC, huguesBouvier approved these changes

2021-03-27 11:07 UTC, merged