Use unique common name for edged-ca cert when apply'ing super-config.
Azure/iotedge pull request #4643
Opened 2021-03-22 02:24 UTC by arsing

This is needed so that multiple Edge devices' edge CA certs in the same PEM
are distinguishable, such as when using Nested Edge.

Also remove hostname check from iotedge-check since it's redundant with
the check in aziotctl-check.

---

TODO:

- Update submodule ref when https://github.com/Azure/iot-identity-service/pull/171 is merged.

2021-03-22 17:01 UTC, gordonwang0 requested changes

2021-03-22 17:18 UTC, arsing commented on edgelet/Cargo.toml
> +aziot-cert-client-async = { path = "/home/arnavion/src/iot-identity-service/cert/aziot-cert-client-async" }
That's why there's a TODO for it in the PR description.

2021-03-22 18:13 UTC, huguesBouvier approved these changes

2021-03-22 19:01 UTC, daprilik submitted a review, later dismissed

2021-03-23 00:18 UTC, massand reviewed
The test-files changes have been done in PR #4556 already, along with the appropriate iotedge logic to use that for setting `auto_reprovision_mode`. I will merge that as soon as you approve so you rebase your PR.

2021-03-23 03:48 UTC, arsing commented
>The test-files changes have been done in PR #4556 already, along with the appropriate iotedge logic to use that for setting `auto_reprovision_mode`. I will merge that as soon as you approve so you rebase your PR.

Yes, if yours goes in first, I'll update this one as necessary.

2021-03-24 00:44 UTC, arsing commented
>>The test-files changes have been done in PR #4556 already, along with the appropriate iotedge logic to use that for setting `auto_reprovision_mode`. I will merge that as soon as you approve so you rebase your PR.
>
>Yes, if yours goes in first, I'll update this one as necessary.

Done.

2021-03-24 16:07 UTC, massand approved these changes

2021-03-24 16:37 UTC, gordonwang0 approved these changes

2021-03-24 17:46 UTC, merged