Cache device provisioning state
Azure/iotedge pull request #4722
Opened 2021-03-29 02:32 UTC by massand

This change caches device provisioning state on each restart. This is used to compare the device provisioning result on each restart with the previous provisioning state, so that modules can be deleted if state has changed.
This fixes the issue of iotedge removing all modules on startup, even when provisioning state was the same.

2021-03-30 21:48 UTC, arsing requested changes

2021-03-30 21:48 UTC, arsing commented on edgelet/aziot-edged/src/lib.rs
> +    file.write_all(digest.as_bytes())
```rust
std::fs::write(path, digest.into_bytes()).context(
    ErrorKind::Initialize(InitializeErrorReason::SaveProvisioning),
)?;
```

2021-04-01 03:21 UTC, massand commented on edgelet/aziot-edged/src/lib.rs
> +    file.write_all(digest.as_bytes())
Fixed

2021-04-01 03:49 UTC, arsing approved these changes

2021-04-01 05:29 UTC, merged