Remove unsafe docker capabilities
Azure/iotedge pull request #5104
Opened 2021-06-11 16:30 UTC by lfitchett

2021-06-16 15:56 UTC, gordonwang0 commented on edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker/CombinedEdgeletConfigProvider.cs
> +            // If customer manually adds the capabilites, don't drop them.
Typo: capabilities

Also, where do these capabilities come from if not the customer? Who else can set them?

2021-06-16 16:10 UTC, gordonwang0 commented on edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker/CombinedEdgeletConfigProvider.cs
> +            if (createOptions.HostConfig?.CapAdd != null)
Couldn't all this be simplified to something like:

```
createOptions.HostConfig.CapDrop =
    new List<string> { "CAP_CHOWN", "CAP_SETUID" }.except(createOptions.HostConfig.CapAdd);
```

(This is just from a quick glance at it, please correct me if I'm wrong)

2021-06-17 13:20 UTC, varunpuranik requested changes
As discussed, we need to put this behind a flag..

2021-06-17 19:06 UTC, lfitchett commented
Replaced by #5126

2021-06-17 19:06 UTC, closed without merging