Device config has allow_privileged flag (#5126)
Azure/iotedge pull request #5159
Opened 2021-06-25 03:25 UTC by lfitchett

2021-06-25 07:12 UTC, arsing approved these changes

2021-06-25 12:33 UTC, varunpuranik requested changes
Still pending shiproom approval..

2021-07-17 14:06 UTC, varunpuranik approved these changes

2021-07-20 17:25 UTC, arsing approved these changes

2021-07-20 17:26 UTC, merged