Update PULL_REQUEST_TEMPLATE.md
Azure/iotedge pull request #5677
Opened 2021-10-12 18:37 UTC by vadim-kovalyov

I was a bit confused by the new PR template, so I'm proposing some change to PR template. Please let me know if that make sense.

## Azure IoT Edge PR checklist:

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines and Best Practices
- [X] I have read the [contribution guidelines](https://github.com/azure/iotedge#contributing).
- [X] Title of the pull request is clear and informative.
- [X] Description of the pull request includes a concise summary of the enhancement or bug fix.

2021-10-13 00:25 UTC, damonbarry requested changes
Almost forgot...

You also need to update the `cut_body_after` option in `.github/.kodiak.toml`

2021-10-15 22:40 UTC, vadim-kovalyov commented on .github/.kodiak.toml
> +cut_body_after = "## Azure IoT Edge PR checklist:"
I assumed that people will just remove this line and write descriptions instead :D

2021-10-15 22:41 UTC, vadim-kovalyov commented on .github/.kodiak.toml
> +cut_body_after = "## Azure IoT Edge PR checklist:"
Should I be more specific that people need to `"remove this line and write your PR Description here"`?

2021-10-16 01:27 UTC, damonbarry commented on .github/.kodiak.toml
> +cut_body_after = "## Azure IoT Edge PR checklist:"
Sure. "Please replace this line with your PR description..."

2021-10-18 20:52 UTC, merged